services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    user: root
    ports:
      - "8001:8000"
    volumes:
      - dynamodb-local:/data

volumes:
  dynamodb-local:
