#!/usr/bin/env bash
# Start the local marketing site (www) with the machine-specific environment
# generated by dev-aws-setup. For the product app, use dev-up-app.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=dev-aws-common.sh
source "$SCRIPT_DIR/dev-aws-common.sh"

dev_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      printf 'Usage: %s [vite-dev options]\n' "$0"
      exit 0
      ;;
    *) dev_args+=("$1") ;;
  esac
  shift
done

require_command npm

marketing_env="$HUMBUGG_DIR/marketing/.env.local"
[[ -f "$marketing_env" ]] ||
  die "Missing $web_env. Run ./humbugg/scripts/dev-aws-setup.sh first."

# The marketing site does not authenticate anyone — sign-in lives in the product app — so it needs
# only where to send somebody who wants to sign in, and where to read the plan catalogue for the
# pricing page.
for key in VITE_APP_ORIGIN VITE_API_BASE_URL; do
  grep -Eq "^${key}=.+" "$marketing_env" ||
    die "Missing $key in $web_env. Run ./humbugg/scripts/dev-aws-setup.sh again."
done

[[ -d "$HUMBUGG_DIR/marketing/node_modules" ]] ||
  die "Marketing site dependencies are not installed. Run npm install in humbugg/marketing first."

exec npm --prefix "$HUMBUGG_DIR/marketing" run dev -- "${dev_args[@]}"
