#!/usr/bin/env bash
# Start the local frontend with the machine-specific environment generated by dev-aws-setup.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=dev-aws-common.sh
source "$SCRIPT_DIR/dev-aws-common.sh"

dev_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      printf 'Usage: %s [frontend-dev options]\n' "$0"
      exit 0
      ;;
    *) dev_args+=("$1") ;;
  esac
  shift
done

require_command npm

frontend_env="$HUMBUGG_DIR/frontend/.env.local"
[[ -f "$frontend_env" ]] ||
  die "Missing $frontend_env. Run ./humbugg/scripts/dev-aws-setup.sh first."

for key in VITE_COGNITO_USER_POOL_ID VITE_COGNITO_CLIENT_ID VITE_AWS_REGION; do
  grep -Eq "^${key}=.+" "$frontend_env" ||
    die "Missing $key in $frontend_env. Run ./humbugg/scripts/dev-aws-setup.sh again."
done

[[ -d "$HUMBUGG_DIR/frontend/node_modules" ]] ||
  die "Frontend dependencies are not installed. Run npm install in humbugg/frontend first."

exec npm --prefix "$HUMBUGG_DIR/frontend" run dev -- "${dev_args[@]}"
