#!/usr/bin/env bash
# Start the local product app (Expo) with the machine-specific environment
# generated by dev-aws-setup. For the marketing site, use dev-up-marketing.sh.
#
# Defaults to the web target because that is what the backend and the marketing
# site are reachable from during ordinary development; pass --ios or --android
# through to Expo to run a simulator instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=dev-aws-common.sh
source "$SCRIPT_DIR/dev-aws-common.sh"

dev_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      printf 'Usage: %s [expo-start options]\n' "$0"
      printf '  Defaults to --web. Pass --ios or --android to target a simulator.\n'
      exit 0
      ;;
    *) dev_args+=("$1") ;;
  esac
  shift
done

# No target given means web.
[[ ${#dev_args[@]} -gt 0 ]] || dev_args=(--web)

require_command npm

app_env="$HUMBUGG_DIR/app/.env.local"
[[ -f "$app_env" ]] ||
  die "Missing $app_env. Run ./humbugg/scripts/dev-aws-setup.sh first."

# Metro inlines EXPO_PUBLIC_* at bundle time, so a missing value here is not a
# runtime warning — it is a build that silently ships an empty Cognito client id.
#
# This list must match what dev-aws-setup.sh WRITES. It did not between #365 and now: the
# hosted-login migration made the pool id and the region app configuration no longer, and
# dev-aws-setup.sh removes both from an existing .env.local — so this loop demanded two keys
# the setup script deletes and the app dev server refused to start on any machine.
for key in EXPO_PUBLIC_COGNITO_CLIENT_ID EXPO_PUBLIC_COGNITO_DOMAIN EXPO_PUBLIC_API_BASE_URL; do
  grep -Eq "^${key}=.+" "$app_env" ||
    die "Missing $key in $app_env. Run ./humbugg/scripts/dev-aws-setup.sh again."
done

[[ -d "$HUMBUGG_DIR/app/node_modules" ]] ||
  die "Product app dependencies are not installed. Run npm install in humbugg/app first."

exec npm --prefix "$HUMBUGG_DIR/app" run start -- "${dev_args[@]}"
