#!/usr/bin/env bash
#
# dev-setup.sh — make this checkout runnable: local env file, backend deps,
# frontend deps.
#
# Safe to run repeatedly: every step checks before it acts, and every step is
# non-fatal on its own. Nothing here writes to AWS; it only READS this machine's
# dev stack to find out what to point the app at. Provision that stack first
# with `dev-aws-setup.sh`.
#
# Deliberately never fatal on a missing stack. A person cloning this repo to fix
# a sanitizer test needs node_modules and a poetry env; they do not need a
# Cognito pool, and a setup script that refuses to run without one is a setup
# script that gets skipped.

set -euo pipefail

log()  { printf '\033[36m[classroom-setup]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[classroom-setup]\033[0m %s\n' "$*"; }

CLASSROOM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$CLASSROOM_DIR/.." && pwd)"
FRONTEND="$CLASSROOM_DIR/frontend"
BACKEND="$CLASSROOM_DIR/backend"
AUTH_SCRIPT="$REPO_ROOT/scripts/github-packages-auth.sh"

# ---------------------------------------------------------------------------
# 1. frontend/.env.local, FROM THIS MACHINE'S DEV STACK.
#
#    Nothing here reads `/classroom/prod/*`. Every page is keyed by the Cognito
#    `sub`, so a local app signed in against the prod pool writes rows beside a
#    real teacher's, under a real teacher's key — which is the outcome the dev
#    stack exists to make impossible.
#
#    Values come from the dev stack's Terraform outputs, not SSM: SSM holds what
#    the deploy workflow wrote, and nothing deploys a dev stack.
# ---------------------------------------------------------------------------
# A subshell, because `dev-aws-common.sh`'s `die` exits and `set -e` here would
# take the whole script down with it. Its `log` output goes to stderr, so what
# is captured is exactly the four values.
if dev_stack="$(
  # shellcheck source=dev-aws-common.sh
  source "$CLASSROOM_DIR/scripts/dev-aws-common.sh"
  load_machine_id false
  load_aws_identity
  load_dev_stack_outputs
  printf '%s\t%s\t%s\t%s\n' "$DEV_CLIENT_ID" "$DEV_AUTH_DOMAIN" "$DEV_POOL_ID" "$DEV_SPA_ORIGIN"
)" 2>/dev/null; then
  IFS=$'\t' read -r CLIENT_ID AUTH_DOMAIN POOL_ID SPA_ORIGIN <<<"$dev_stack"

  cat > "$FRONTEND/.env.local" <<ENVFILE
# Generated by classroom/scripts/dev-setup.sh from this machine's dev stack.
# Do not edit by hand — re-run the script instead. Git-ignored.
#
# This is the DEV Cognito pool and its Managed Login host. Local development
# does not sign in against production; see the note in dev-setup.sh.
#
# Pool $POOL_ID
VITE_API_URL=http://localhost:8001/api
VITE_COGNITO_DOMAIN=$AUTH_DOMAIN
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
ENVFILE
  log "wrote frontend/.env.local (dev pool $POOL_ID, sign-in at $AUTH_DOMAIN)"
  log "the app client registers $SPA_ORIGIN — serve the SPA there or the redirect fails"
else
  # Three distinct causes, one message, and that is deliberate: the remedy for
  # all of them starts with the same command, and this script should not make a
  # person diagnose which of the three it hit.
  warn "no dev stack readable — skipping frontend/.env.local."
  warn "  Either this machine has no working AWS credentials, or it has never"
  warn "  provisioned a stack. Check the first with:"
  warn "    aws sts get-caller-identity"
  warn "  then provision with:"
  warn "    ./classroom/scripts/dev-aws-setup.sh"
  warn "  Nothing here points at production."
fi

# ---------------------------------------------------------------------------
# 2. The backend's Poetry environment.
#
#    Poetry is pinned to 2.2.1 in both `classroom-pr.yml` and
#    `backend/Dockerfile`, so a local failure means the same thing there.
#    Installed through uv when it is missing, which is how studio does it.
#
#    `--with dev` matters: PyJWT lives in that group and the local dev server
#    cannot verify a token without it. `--no-root` because the backend is not a
#    package — the Dockerfile copies `classroom_core` in rather than installing
#    it.
# ---------------------------------------------------------------------------
export PATH="$HOME/.local/bin:$PATH"

if ! command -v poetry >/dev/null 2>&1; then
  if command -v uv >/dev/null 2>&1; then
    log "poetry is missing — installing 2.2.1 (the version CI and the image pin)."
    uv tool install poetry==2.2.1
    hash -r 2>/dev/null || true
  else
    warn "poetry and uv are both missing, so the backend has no environment."
    warn "  The shared installer has uv: ./scripts/dev-setup.sh (repo root)"
  fi
fi

if command -v poetry >/dev/null 2>&1; then
  log "installing backend dependencies (poetry install --with dev)..."
  if (cd "$BACKEND" && poetry install --with dev --no-root --no-interaction >/dev/null 2>&1); then
    log "backend environment ready"
  else
    warn "poetry install failed in classroom/backend. Re-run it directly to see why:"
    warn "  cd classroom/backend && poetry install --with dev --no-root"
  fi
fi

# ---------------------------------------------------------------------------
# 3. frontend/node_modules.
#
#    `dev-up.sh` goes straight to `npm run dev`, and CI does its own `npm ci`, so
#    on a clean clone the first symptom is `vite: not found` — vite, tsc and
#    eslint are all local devDependencies and there is no global fallback.
#
#    `@ansavva/design-system` comes from GitHub Packages, which has no anonymous
#    read, so the install needs a `read:packages` token in NODE_AUTH_TOKEN — the
#    committed `frontend/.npmrc` already reads it from there.
# ---------------------------------------------------------------------------
# Up to date when node_modules' own lockfile is at least as new as the repo's.
# npm writes node_modules/.package-lock.json on every install, so this is the
# cheap check that makes re-running free.
frontend_is_current() {
  [ -d "$FRONTEND/node_modules" ] &&
    [ -f "$FRONTEND/node_modules/.package-lock.json" ] &&
    [ ! "$FRONTEND/package-lock.json" -nt "$FRONTEND/node_modules/.package-lock.json" ]
}

if ! command -v npm >/dev/null 2>&1; then
  warn "npm is missing — skipping frontend deps. The shared installer has it:"
  warn "  ./scripts/dev-setup.sh (repo root)"
elif frontend_is_current; then
  log "frontend node_modules already current"
else
  # `--check` FIRST, and never a bare `--export`. In its ensure and export modes
  # that script falls through to `gh auth refresh --scopes read:packages`, which
  # is INTERACTIVE — it prompts and waits for a browser flow. `--check` only
  # inspects env vars, needs no input and exits non-zero quickly.
  #
  # A developer machine usually already has the scope on its `gh` login, but
  # `--check` reads only env vars and would miss it. So hand gh's existing token
  # to `--check` as one of the variables it does read. Reading a token is not
  # refreshing one: this never prompts.
  if [ -z "${GITHUB_PACKAGES_TOKEN:-}" ] && command -v gh >/dev/null 2>&1; then
    gh_existing="$(gh auth token 2>/dev/null || true)"
    [ -n "$gh_existing" ] && export GITHUB_PACKAGES_TOKEN="$gh_existing"
    unset gh_existing
  fi

  if [ -x "$AUTH_SCRIPT" ] && "$AUTH_SCRIPT" --check >/dev/null 2>&1; then
    eval "$("$AUTH_SCRIPT" --export 2>/dev/null || true)"
    log "GitHub Packages read access confirmed"
  fi

  if [ -z "${NODE_AUTH_TOKEN:-}" ]; then
    warn "no read:packages token, so @ansavva/design-system cannot be installed."
    warn "  Fix it with either of these, then re-run this script:"
    warn "    ./scripts/github-packages-auth.sh                      # interactive, via gh"
    warn "    export GITHUB_PACKAGES_TOKEN=<PAT with read:packages>  # CI / cloud agent"
    warn "  Until then 'npm run typecheck', 'npm run lint' and 'npm run dev' all"
    warn "  fail with a missing binary."
  else
    log "installing frontend node_modules (npm ci)..."
    # `npm ci` rather than `install`: it is what CI runs, and it refuses to
    # silently rewrite package-lock.json underneath a dev environment.
    if (cd "$FRONTEND" && npm ci --no-audit --no-fund >/dev/null 2>&1); then
      log "frontend node_modules installed"
    else
      warn "npm ci failed in classroom/frontend. Re-run it directly to see why:"
      warn "  cd classroom/frontend && npm ci"
    fi
  fi
fi

log "done."
