// Writes Studio's mark to `src/assets/aperture.svg`, the file the browser tab reads.
//
// `src/utils/aperture.ts` IS the drawing — one function, solved at whatever
// openness it is asked for, shared by the header mark and every frame of the
// loading animation. A favicon cannot import it: it is a file the browser
// fetches before any script runs. So it is generated FROM it rather than drawn
// a second time, and `npm run mark:check` fails the PR when the two disagree.
//
// `src/assets/aperture.svg` IS GENERATED — do not hand-edit it. It carries its own
// banner; SVG has comment syntax, unlike the Cognito settings document next
// door.
//
// Node runs this file directly by stripping the types, which is why the import
// below names a `.ts` path and why nothing in that module may touch React.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { blades } from '../src/utils/aperture.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../src/assets/aperture.svg');
const REGEN = 'npm run mark';

// Wide open, and a wide gap with it. A favicon is drawn at 16px more often than
// anything else in this repo, and at that size the hairline the header can
// afford closes up into a solid disc.
const OPENNESS = 1;
const GAP = 5;

// `#eeeeee` is `--color-neutral-12`, the ink this app paints its chrome in. The
// tab strip is not the app and does not read `app.css`, so this one value is
// copied rather than resolved — a favicon that inherited `currentColor` would
// come out black on every browser that renders it against a dark tab.
const INK = '#eeeeee';

function render(): string {
  const paths = blades(OPENNESS, GAP)
    .map((d) => `  <path d="${d}" />`)
    .join('\n');
  return [
    `<!-- GENERATED by ${REGEN} — edit src/utils/aperture.ts, not this file. -->`,
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="' + INK + '">',
    paths,
    '</svg>',
    '',
  ].join('\n');
}

const svg = render();

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error(`${OUT} is missing. Run \`${REGEN}\`.`);
    process.exit(1);
  }
  if (current !== svg) {
    console.error(`${OUT} is out of step with src/utils/aperture.ts. Run \`${REGEN}\`.`);
    process.exit(1);
  }
  console.log('aperture.svg matches the geometry.');
} else {
  writeFileSync(OUT, svg);
  console.log(`Wrote ${OUT}`);
}
