"""`studio convert` — re-encode an image in the media tree so an engine will accept it.

Engines disagree about image formats, and the mismatch bites at the seam between
them: **GPT Image writes `.webp` by default, and Kling accepts only
`.jpg/.jpeg/.png`** — so a still generated by `studio-image` cannot be handed
straight to `studio-kling` as a start frame. Seedance is permissive; Nano Banana
writes `.jpg`/`.png`.

This converts an existing S3 object (or a run's output) and writes the result
back into the tree — by default into the **project's input pool**, which is
where working material belongs. The source is never modified: a run's output is
append-only history, so it is copied, not re-encoded in place.

  # a run's output -> PNG in the project's input pool
  uv run s3_convert.py --run <project>/latest#1 --to png --add-input <project>

  # target an engine rather than naming a format
  uv run s3_convert.py --run <project>/latest#1 --for kling --add-input <project>

  # explicit source and destination
  uv run s3_convert.py --key projects/<p>/input/<p>_in_3.webp \
      --to png --dest-key projects/<p>/input/<p>_in_3.png

Prints the new S3 key. With `--for`, an already-compatible image is left alone
and its existing key is printed, so the command is safe to run unconditionally.
"""
from __future__ import annotations

import io
import os
import sys

from studio_pipeline.store import paths as P  # noqa: E402
from studio_pipeline.store import runs as R  # noqa: E402
from studio_pipeline.store import s3 as s3c  # noqa: E402

from studio_pipeline.engine import registry as REG  # noqa: E402
from types import SimpleNamespace

import click

# What each model accepts is registry data — `--for` takes any model key, so a
# model added with `studio-add-model` is convertible for without touching this file.
EXT_FOR = {"png": ".png", "jpg": ".jpg", "jpeg": ".jpg", "webp": ".webp"}
PIL_FORMAT = {".png": "PNG", ".jpg": "JPEG", ".webp": "WEBP"}
CONTENT_TYPE = {".png": "image/png", ".jpg": "image/jpeg", ".webp": "image/webp"}


def die(msg: str) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def next_input_index(s3, project: str) -> int:
    """Continue the project's input-pool numbering (<project>_in_<n>)."""
    import re

    pat = re.compile(rf"^{re.escape(project)}_in_(\d+)\.")
    hi = 0
    for key in s3c.list_keys(s3, P.input_prefix(project)):
        m = pat.match(os.path.basename(key))
        if m:
            hi = max(hi, int(m.group(1)))
    return hi + 1


@click.command(help=__doc__)
@click.option("--add-input", help=("Write into PROJECT's input pool as <project>_in_<n> (the usual "
              "destination)."))
@click.option("--dest-key", help="Explicit destination S3 key instead.")
@click.option("--for", "for_", type=click.Choice(["gpt-image-1.5", "gpt-image-2", "kling", "nano-banana-2", "nano-banana-pro", "seedance"]), help="Convert only if this engine would reject the current format.")
@click.option("--key", help="Source S3 key (full).")
@click.option("--project", help="Default project for a bare runref.")
@click.option("--quality", type=int, default=95, help="JPEG/WebP quality (default 95).")
@click.option("--run", help="Source runref, e.g. <name>/latest#1.")
@click.option("--to", type=click.Choice(["jpeg", "jpg", "png", "webp"]), help="Target format.")
def main(add_input, dest_key, for_, key, project, quality, run, to):
    return _run(SimpleNamespace(add_input=add_input, dest_key=dest_key, engine=for_, key=key, project=project, quality=quality, run=run, to=to))


def _run(args):

    if not args.add_input and not args.dest_key:
        die("choose a destination: --add-input PROJECT (usual) or --dest-key KEY.")

    s3 = s3c.client()

    # --- resolve the source -------------------------------------------------
    if args.run:
        try:
            keys = R.resolve_output_keys(s3, args.run, args.project, kinds=R.IMG_EXTS)
        except R.RunError as e:
            die(str(e))
        if len(keys) > 1:
            die(f"runref matched {len(keys)} images; add #N to pick one: {keys}")
        key = keys[0]
    else:
        key = args.key
    ext = os.path.splitext(key)[1].lower()

    # --- decide the target format ------------------------------------------
    if args.engine:
        allowed = REG.accepts_ext(REG.get(args.engine))
        if ext in allowed:
            # Already fine — print the untouched key so callers can chain safely.
            print(key)
            print(f"{os.path.basename(key)} is already accepted by {args.engine}; "
                  "nothing converted.", file=sys.stderr)
            return 0
        target_ext = ".png"  # lossless, and accepted by every engine here
    else:
        target_ext = EXT_FOR[args.to]

    if ext == target_ext:
        print(key)
        print("source is already in the target format; nothing converted.", file=sys.stderr)
        return 0

    # --- convert (source is never modified) ---------------------------------
    from PIL import Image

    body = s3.get_object(Bucket=s3c.BUCKET, Key=key)["Body"].read()
    im = Image.open(io.BytesIO(body))
    if target_ext == ".jpg" and im.mode in ("RGBA", "P", "LA"):
        im = im.convert("RGB")  # JPEG has no alpha channel
    buf = io.BytesIO()
    save_kwargs = {"quality": args.quality} if target_ext in (".jpg", ".webp") else {}
    im.save(buf, PIL_FORMAT[target_ext], **save_kwargs)
    data = buf.getvalue()

    # --- destination --------------------------------------------------------
    if args.dest_key:
        dst = args.dest_key
    else:
        project = args.add_input
        n = next_input_index(s3, project)
        dst = P.input_key(project, n, target_ext)

    s3.put_object(Bucket=s3c.BUCKET, Key=dst, Body=data,
                  ContentType=CONTENT_TYPE[target_ext])
    print(dst)
    print(f"converted {os.path.basename(key)} ({ext}, {len(body)} B) -> "
          f"{os.path.basename(dst)} ({target_ext}, {len(data)} B); source untouched",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
