AWSTemplateFormatVersion: '2010-09-09'
Description: Humbugg frontend static hosting via S3 + CloudFront with /app path routing and /api proxy

Parameters:
  StackName:
    Type: String
  DomainName:
    Type: String
    Description: Fully qualified domain (e.g., humbugg.andreas.services)
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID for andreas.services
  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 covering the domain
  ApiDomainName:
    Type: String
    Description: API Gateway execute-api domain (e.g., abc123.execute-api.us-east-1.amazonaws.com)
  ApiStageName:
    Type: String
    Description: API Gateway stage name (e.g., prod)
  AppPrefix:
    Type: String
    Default: /app
    Description: URL path prefix where the SPA will live

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - Distribution
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${SiteBucket}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}

  RewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub ${StackName}-rewrite
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;
          if (uri.startsWith('/api/')) {
            return request;
          }
          var prefix = '${AppPrefix}';
          if (!uri.startsWith(prefix)) {
            if (uri === '/' || uri === '') {
              request.uri = prefix + '/index.html';
              return request;
            }
            if (uri.startsWith('/')) {
              uri = prefix + uri;
            } else {
              uri = prefix + '/' + uri;
            }
          }
          if (uri === prefix || uri === prefix + '/') {
            request.uri = prefix + '/index.html';
          } else {
            request.uri = uri;
          }
          return request;
        }

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        Origins:
          - Id: SiteOrigin
            DomainName: !Sub ${SiteBucket}.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
          - Id: ApiOrigin
            DomainName: !Ref ApiDomainName
            OriginPath: !Sub /${ApiStageName}
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPPort: 80
              HTTPSPort: 443
        DefaultCacheBehavior:
          TargetOriginId: SiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RewriteFunction.FunctionARN
        CacheBehaviors:
          - PathPattern: '/api/*'
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: !Sub ${AppPrefix}/index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: !Sub ${AppPrefix}/index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront zone ID

Outputs:
  SiteBucketName:
    Description: Upload SPA assets to this bucket (under /app/)
    Value: !Ref SiteBucket
  DistributionId:
    Value: !Ref Distribution
  DistributionDomain:
    Value: !GetAtt Distribution.DomainName
