"""`studio convert` — re-encode an image in the media tree so an engine will accept it.

Engines disagree about image formats, and the mismatch bites at the seam between
them: **GPT Image writes `.webp` by default, and Kling accepts only
`.jpg/.jpeg/.png`** — so a still generated by `studio-media-image` cannot be handed
straight to `studio-media-kling` as a start frame. Seedance is permissive; Nano Banana
writes `.jpg`/`.png`.

This converts an existing object (or a run's output) and writes the result back
into the tree — by default into the **project's input pool**, which is where
working material belongs. The source is never modified: a run's output is
append-only history, so it is copied, not re-encoded in place.

THE PIXELS ARE PUSHED AROUND BY THE SERVICE, SYNCHRONOUSLY
-----------------------------------------------------------
**Pillow lives in the API image, not this wheel.** This command is one
`POST /api/images/convert`: the bytes never come down and never go back up, so
a conversion is a request rather than a download, a decode, an encode and an
upload.

**It is not on the render queue, and that was a decision rather than an
oversight.** Stitching went to a worker because a re-encode is minutes and
because ffmpeg is 80 MB nothing else should carry. A conversion is sub-second on
one image, so an enqueue plus two polls would cost more wall clock than the work
— and Pillow is 3 MB. `backend/studio_core/routes/images.py` states the split.

What stays on this side is the **decision**: `--for kling` is a registry lookup
that answers "is a conversion needed at all", and a source that is already
acceptable makes no request. A route answering "nothing to do" with a node id it
did not create would be a strange thing for a POST to do.

  # a run's output -> PNG in the project's input pool
  studio convert --run <project>/latest#1 --to png --add-input <project>

  # target an engine rather than naming a format
  studio convert --run <project>/latest#1 --for kling --add-input <project>

  # explicit source and destination
  studio convert --key projects/<p>/input/<p>_in_3.webp \
      --to png --dest-key projects/<p>/input/<p>_in_3.png

Prints the new name path. With `--for`, an already-compatible image is left
alone and its existing path is printed, so the command is safe to run
unconditionally.
"""
from __future__ import annotations

import os
import sys

import click

from studio_pipeline.errors import die, reports
from studio_pipeline.adapters import api, entities, store
from studio_pipeline.domain import paths as P
from studio_pipeline.domain import projects as PROJECTS
from studio_pipeline.domain import runs as R
from studio_pipeline.engine import registry as REG

# What each model accepts is registry data — `--for` takes any model key, so a
# model added with `studio-media-add-model` is convertible for without touching this file.
EXT_FOR = {"png": ".png", "jpg": ".jpg", "jpeg": ".jpg", "webp": ".webp"}
# `PIL_FORMAT` and `CONTENT_TYPE` sat beside it until now. Both were arguments to
# an encode this process performed; the route performs it, so the target format
# travels as the word a person typed and the content type is the service's to
# decide from it. Only the extension table is still read here, and only to answer
# "is a conversion needed at all".



def input_pool(project: str) -> str:
    """The project's input pool folder node — where converted material belongs.

    **`add_inputs` is not gone through**: the bytes never reach this process, so
    there is nothing to stage to a temp file and no name for this module to
    invent.

    The API writes the file now and `create_numbered` resolves a clash, so a
    second conversion of the same source lands `frame (2).png` beside the first.
    The naming rule has one implementation again, and it is the catalog's.
    """
    return store.ensure_child_folder(
        PROJECTS.require_project(project)["root"], P.INPUT_FOLDER)["id"]


def destination(add_input: str | None, dest_key: str | None
                ) -> tuple[str | None, str | None]:
    """-> (destination folder node, filename), from whichever flag was given.

    `--dest-key` is a NAME PATH, so its parent has to exist before a file can
    hang off it. Folders were free in S3 — a key with slashes produced the
    appearance of one — and are catalog rows now, and `--dest-key` is the flag
    most likely to name somewhere nothing has ever written. A path with no slash
    sits in the library root, which is already there; asking for it would try to
    create a folder named after the file. **It now lands beside the source
    instead**, because the route resolves an unnamed destination to the source's
    own parent — a small change, stated rather than hidden, and reachable only by
    a `--dest-key` with no slash in it.
    """
    if dest_key:
        clean = dest_key.strip("/")
        if "/" in clean:
            parent, name = clean.rsplit("/", 1)
            return store.folder(parent)["id"], name
        return None, clean
    return input_pool(add_input), None


def _source_name(key: str) -> str:
    """The filename behind `--key`, whether it named a node or a name path.

    Only the EXTENSION is wanted — it decides whether a conversion is needed at
    all — and a node id carries none, so the id has to be resolved to a record
    to find it. A name path already is one.
    """
    if key.startswith("node-"):
        try:
            return store.node(key).get("name") or ""
        except api.NotFound:
            die(f"no such node: {key}")
    return key


@click.command(help=__doc__)
@click.option("--add-input", help=("Write into PROJECT's input pool as <project>_in_<n> (the usual "
              "destination)."))
# `--dest-key` / `--key` and their help text say "S3 key" and take a NAME PATH.
# Both are frozen: `tests/contracts/cli_surface_reference.json` is the argparse-era capture
# of the CLI surface and `test_help_text_survived` compares these strings against
# it, so correcting the wording here is a contract change and not a comment fix.
@click.option("--dest-key", help="Explicit destination S3 key instead.")
@click.option("--for", "for_", type=click.Choice(["gpt-image-1.5", "gpt-image-2", "kling", "nano-banana-2", "nano-banana-pro", "seedance"]), help="Convert only if this engine would reject the current format.")
@click.option("--key", help="Source S3 key (full).")
@click.option("--project", help="Default project for a bare runref.")
@click.option("--quality", type=int, default=95, help="JPEG/WebP quality (default 95).")
@click.option("--run", help="Source runref, e.g. <name>/latest#1.")
@click.option("--to", type=click.Choice(["jpeg", "jpg", "png", "webp"]), help="Target format.")
# **Reported rather than raised.** The route reads the source, so a missing one
# arrives as an `api.NotFound` carrying the path — and without this the
# commonest failure of this command is a traceback instead of a sentence.
@reports(api.NotFound, api.Forbidden, api.ApiError, R.RunError)
def convert(add_input, dest_key, for_, key, project, quality, run, to):
    if not add_input and not dest_key:
        die("choose a destination: --add-input PROJECT (usual) or --dest-key KEY.")

    # --- resolve the source -------------------------------------------------
    if run:
        try:
            nodes = R.resolve_output_nodes(run, project, kinds=R.IMG_EXTS)
        except R.RunError as e:
            die(str(e))
        if len(nodes) > 1:
            die(f"runref matched {len(nodes)} images; add #N to pick one: {nodes}")
        # A runref resolves to a NODE now, so `key` below holds a node id where
        # it held a path. The flag is still spelled `--key` and still documented
        # as an S3 key: `cli_surface_reference.json` is the argparse-era capture
        # and `test_help_text_survived` compares those strings, so the wording is
        # a contract change rather than a comment fix. What it accepts widened;
        # what it is called did not.
        key = nodes[0]
    ext = os.path.splitext(_source_name(key))[1].lower()

    # --- decide the target format ------------------------------------------
    if for_:
        allowed = REG.accepts_ext(REG.get(for_))
        if ext in allowed:
            # Already fine — print the untouched key so callers can chain safely.
            print(key)
            print(f"{os.path.basename(_source_name(key))} is already accepted by {for_}; "
                  "nothing converted.", file=sys.stderr)
            return 0
        target_ext = ".png"  # lossless, and accepted by every engine here
    else:
        target_ext = EXT_FOR[to]

    if ext == target_ext:
        print(key)
        print("source is already in the target format; nothing converted.", file=sys.stderr)
        return 0

    # --- the conversion is a request now ------------------------------------
    #
    # `--key` may hold a name path rather than a node id, so it is resolved to a
    # node first: the route takes a node, because a node is the one address a
    # rename cannot invalidate.
    node = key if key.startswith("node-") else store.resolve(key)["id"]
    folder, name = destination(add_input, dest_key)
    reply = entities.convert_image(node, to=to or ("png" if for_ else None),
                                   dest=folder, name=name, quality=quality)

    image = reply["image"]
    print(image["node"])
    # `_source_name`, not the raw `key`: with a runref the key is a node id, and
    # `os.path.basename` of a uuid is the uuid — which tells a reader nothing
    # about which image was converted.
    print(f"converted {os.path.basename(_source_name(key))} "
          f"({ext}, {reply['source']['bytes']} B) -> "
          f"{image.get('name')} ({target_ext}, {reply['bytes']} B); source untouched",
          file=sys.stderr)
    return 0
