"""`studio convert` — re-encode an image in the media tree so an engine will accept it.

Engines disagree about image formats, and the mismatch bites at the seam between
them: **GPT Image writes `.webp` by default, and Kling accepts only
`.jpg/.jpeg/.png`** — so a still generated by `studio-media-image` cannot be handed
straight to `studio-media-kling` as a start frame. Seedance is permissive; Nano Banana
writes `.jpg`/`.png`.

This converts an existing object (or a run's output) and writes the result back
into the tree — by default into the **project's input pool**, which is where
working material belongs. The source is never modified: a run's output is
append-only history, so it is copied, not re-encoded in place.

Everything moves through `adapters/store`, so nothing here holds a bucket name
or a credential. Two consequences worth knowing:

  * The **pool numbering is `projects.add_inputs`'**, not a second copy of it.
    The bytes are in memory and that function takes local paths, so they are
    staged to a temp file — cheaper than a second implementation of the naming
    rule, which is what this module used to carry.
  * `--dest-key` **ensures the destination folder first.** Folders were free in
    S3 (a key with slashes in it produced the appearance of one) and are
    catalog rows now, so a write into a folder nothing has created yet fails on
    a parent that does not exist.

  # a run's output -> PNG in the project's input pool
  studio convert --run <project>/latest#1 --to png --add-input <project>

  # target an engine rather than naming a format
  studio convert --run <project>/latest#1 --for kling --add-input <project>

  # explicit source and destination
  studio convert --key projects/<p>/input/<p>_in_3.webp \
      --to png --dest-key projects/<p>/input/<p>_in_3.png

Prints the new name path. With `--for`, an already-compatible image is left
alone and its existing path is printed, so the command is safe to run
unconditionally.
"""
from __future__ import annotations

import io
import os
import sys
import tempfile

import click

from studio_pipeline.errors import die
from studio_pipeline.adapters import api, store
from studio_pipeline.domain import projects as PROJECTS
from studio_pipeline.domain import runs as R
from studio_pipeline.engine import registry as REG

# What each model accepts is registry data — `--for` takes any model key, so a
# model added with `studio-media-add-model` is convertible for without touching this file.
EXT_FOR = {"png": ".png", "jpg": ".jpg", "jpeg": ".jpg", "webp": ".webp"}
PIL_FORMAT = {".png": "PNG", ".jpg": "JPEG", ".webp": "WEBP"}
CONTENT_TYPE = {".png": "image/png", ".jpg": "image/jpeg", ".webp": "image/webp"}



def _into_input_pool(project: str, data: bytes, ext: str) -> str:
    """Write converted bytes into a project's input pool, and return the key.

    **`projects.add_inputs` owns the numbering**, and this module used to carry
    a second copy of it. That function takes local paths — the pool is normally
    fed from disk — so the bytes are staged to a temp file rather than
    reimplementing `<project>_in_<n>`. It also ensures the pool folder, which a
    project that has never had an input does not have.

    The staged basename is thrown away; only its extension survives, because
    that is what the pool's own name is built from.
    """
    with tempfile.TemporaryDirectory(prefix="convert-") as tmp:
        staged = os.path.join(tmp, f"converted{ext}")
        with open(staged, "wb") as fh:
            fh.write(data)
        return PROJECTS.add_inputs(PROJECTS.require_project(project),
                                   [staged])[0]["node"]


def _source_name(key: str) -> str:
    """The filename behind `--key`, whether it named a node or a name path.

    Only the EXTENSION is wanted — it decides whether a conversion is needed at
    all — and a node id carries none, so the id has to be resolved to a record
    to find it. A name path already is one.
    """
    if key.startswith("node-"):
        try:
            return store.node(key).get("name") or ""
        except api.NotFound:
            die(f"no such node: {key}")
    return key


@click.command(help=__doc__)
@click.option("--add-input", help=("Write into PROJECT's input pool as <project>_in_<n> (the usual "
              "destination)."))
# `--dest-key` / `--key` and their help text say "S3 key" and take a NAME PATH.
# Both are frozen: `tests/contracts/cli_surface_reference.json` is the argparse-era capture
# of the CLI surface and `test_help_text_survived` compares these strings against
# it, so correcting the wording here is a contract change and not a comment fix.
@click.option("--dest-key", help="Explicit destination S3 key instead.")
@click.option("--for", "for_", type=click.Choice(["gpt-image-1.5", "gpt-image-2", "kling", "nano-banana-2", "nano-banana-pro", "seedance"]), help="Convert only if this engine would reject the current format.")
@click.option("--key", help="Source S3 key (full).")
@click.option("--project", help="Default project for a bare runref.")
@click.option("--quality", type=int, default=95, help="JPEG/WebP quality (default 95).")
@click.option("--run", help="Source runref, e.g. <name>/latest#1.")
@click.option("--to", type=click.Choice(["jpeg", "jpg", "png", "webp"]), help="Target format.")
def convert(add_input, dest_key, for_, key, project, quality, run, to):
    if not add_input and not dest_key:
        die("choose a destination: --add-input PROJECT (usual) or --dest-key KEY.")

    # --- resolve the source -------------------------------------------------
    if run:
        try:
            nodes = R.resolve_output_nodes(run, project, kinds=R.IMG_EXTS)
        except R.RunError as e:
            die(str(e))
        if len(nodes) > 1:
            die(f"runref matched {len(nodes)} images; add #N to pick one: {nodes}")
        # A runref resolves to a NODE now, so `key` below holds a node id where
        # it held a path. The flag is still spelled `--key` and still documented
        # as an S3 key: `cli_surface_reference.json` is the argparse-era capture
        # and `test_help_text_survived` compares those strings, so the wording is
        # a contract change rather than a comment fix. What it accepts widened;
        # what it is called did not.
        key = nodes[0]
    ext = os.path.splitext(_source_name(key))[1].lower()

    # --- decide the target format ------------------------------------------
    if for_:
        allowed = REG.accepts_ext(REG.get(for_))
        if ext in allowed:
            # Already fine — print the untouched key so callers can chain safely.
            print(key)
            print(f"{os.path.basename(_source_name(key))} is already accepted by {for_}; "
                  "nothing converted.", file=sys.stderr)
            return 0
        target_ext = ".png"  # lossless, and accepted by every engine here
    else:
        target_ext = EXT_FOR[to]

    if ext == target_ext:
        print(key)
        print("source is already in the target format; nothing converted.", file=sys.stderr)
        return 0

    # --- convert (source is never modified) ---------------------------------
    from PIL import Image

    try:
        body = store.read_node(key) if key.startswith("node-") else store.read(key)
    except api.NotFound:
        # Named, because the commonest source of one is a runref that resolved
        # to a key nothing wrote — and a traceback does not say which key.
        die(f"no such object: {key}")
    im = Image.open(io.BytesIO(body))
    if target_ext == ".jpg" and im.mode in ("RGBA", "P", "LA"):
        im = im.convert("RGB")  # JPEG has no alpha channel
    buf = io.BytesIO()
    save_kwargs = {"quality": quality} if target_ext in (".jpg", ".webp") else {}
    im.save(buf, PIL_FORMAT[target_ext], **save_kwargs)
    data = buf.getvalue()

    # --- destination --------------------------------------------------------
    if dest_key:
        dst = dest_key.strip("/")
        # The parent has to exist before a file can hang off it. S3 made the
        # folder out of the key's slashes; the catalog does not, and `--dest-key`
        # is the flag most likely to name somewhere nothing has written yet.
        # A key with no slash sits in the library root, which is already there —
        # asking for it would try to create a folder named after the file.
        if "/" in dst:
            store.folder(dst.rsplit("/", 1)[0])
        store.write(dst, data, content_type=CONTENT_TYPE[target_ext])
    else:
        dst = _into_input_pool(add_input, data, target_ext)

    print(dst)
    # `_source_name`, not the raw `key`: with a runref the key is a node id, and
    # `os.path.basename` of a uuid is the uuid — which tells a reader nothing
    # about which image was converted.
    print(f"converted {os.path.basename(_source_name(key))} ({ext}, {len(body)} B) -> "
          f"{os.path.basename(dst)} ({target_ext}, {len(data)} B); source untouched",
          file=sys.stderr)
    return 0
