[tool.poetry]
name = "scout-events-api"
version = "0.1.0"
description = "Scout events API Lambda"
authors = []
packages = []

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "1.26.137"

[tool.poetry.group.dev.dependencies]
moto = {version = "4.2.14", extras = ["dynamodb"]}
pytest = "7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
