from dataclasses import dataclass
from typing import Optional, List
from datetime import datetime

from src.config.replicate_config import replicate_config
from src.config.generation_models_config import generation_models_config

@dataclass
class ModelProject:
    """
    ModelProject model - represents a user's AI model training project
    Stored in MongoDB with images stored in S3

    State machine:
    DRAFT -> TRAINING -> READY
    """
    id: str  # UUID generated by application or MongoDB _id
    name: str
    subject_name: str  # Name of the subject being trained (e.g., "John", "MyDog")
    user_id: str  # Cognito user ID (sub claim)
    status: str = "DRAFT"  # Project status for workflow management
    DEFAULT_MODEL_TYPE = replicate_config.get_default_profile()

    @staticmethod
    def _get_all_valid_model_types() -> List[str]:
        """Get all valid model types (training + generation)"""
        model_types = []

        # Add training model types
        model_types.extend(replicate_config.get_profile_ids())

        # Add generation model types from all providers
        for provider in generation_models_config.get_providers():
            model_types.extend(generation_models_config.get_profile_ids(provider))

        return model_types

    VALID_MODEL_TYPES = _get_all_valid_model_types.__func__()

    model_type: str = DEFAULT_MODEL_TYPE
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    replicate_model_id: Optional[str] = None

    # Legacy field for backwards compatibility (no longer used with MongoDB)
    key: Optional[str] = None

    # Valid status values
    STATUS_DRAFT = "DRAFT"
    STATUS_TRAINING = "TRAINING"
    STATUS_READY = "READY"

    VALID_STATUSES = [
        STATUS_DRAFT,
        STATUS_TRAINING,
        STATUS_READY
    ]

    def to_dict(self):
        """Convert to dictionary for MongoDB storage"""
        return {
            '_id': self.id,
            'name': self.name,
            'subject_name': self.subject_name,
            'user_id': self.user_id,
            'status': self.status,
            'model_type': self.model_type or self.DEFAULT_MODEL_TYPE,
            'replicate_model_id': self.replicate_model_id,
            'created_at': self.created_at or datetime.utcnow(),
            'updated_at': self.updated_at or datetime.utcnow()
        }

    @staticmethod
    def from_dict(data: dict) -> 'ModelProject':
        """Create ModelProject from MongoDB document"""
        return ModelProject(
            id=str(data.get('_id')),
            name=data.get('name'),
            subject_name=data.get('subject_name'),
            user_id=data.get('user_id'),
            status=data.get('status', 'DRAFT'),
            model_type=ModelProject._normalize_model_type(data.get('model_type')),
            created_at=data.get('created_at'),
            updated_at=data.get('updated_at'),
            replicate_model_id=data.get('replicate_model_id')
        )

    @staticmethod
    def _normalize_model_type(value: Optional[str]) -> str:
        if not value:
            return ModelProject.DEFAULT_MODEL_TYPE
        if value not in ModelProject.VALID_MODEL_TYPES:
            return ModelProject.DEFAULT_MODEL_TYPE
        return value

    def requires_training(self) -> bool:
        """
        Determine if this model type requires training

        Returns:
            True if the model is a training-based model (Replicate training models)
            False if the model is a generation-only model (Stability AI, Replicate Flux Pro)
        """
        # Check if it's a training model (from replicate training configs)
        if self.model_type in replicate_config.get_profile_ids():
            return True

        # Otherwise it's a generation-only model
        return False

    def get_provider(self) -> str:
        """
        Get the provider for this model type

        Returns:
            Provider name (e.g., 'replicate', 'stability_ai')
        """
        # Check training models first
        if self.model_type in replicate_config.get_profile_ids():
            return 'replicate'

        # Check generation models
        for provider in generation_models_config.get_providers():
            if self.model_type in generation_models_config.get_profile_ids(provider):
                return provider

        # Default to replicate
        return 'replicate'
