from dataclasses import dataclass
from typing import Optional
from datetime import datetime

@dataclass
class Project:
    """
    Project model - represents a user's AI training project
    Stored in MongoDB with images stored in S3
    """
    id: str  # UUID generated by application or MongoDB _id
    name: str
    subject_name: str  # Name of the subject being trained (e.g., "John", "MyDog")
    user_id: str  # Cognito user ID (sub claim)
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    # Legacy field for backwards compatibility (no longer used with MongoDB)
    key: Optional[str] = None

    def to_dict(self):
        """Convert to dictionary for MongoDB storage"""
        return {
            '_id': self.id,
            'name': self.name,
            'subject_name': self.subject_name,
            'user_id': self.user_id,
            'created_at': self.created_at or datetime.utcnow(),
            'updated_at': self.updated_at or datetime.utcnow()
        }

    @staticmethod
    def from_dict(data: dict) -> 'Project':
        """Create Project from MongoDB document"""
        return Project(
            id=str(data.get('_id')),
            name=data.get('name'),
            subject_name=data.get('subject_name'),
            user_id=data.get('user_id'),
            created_at=data.get('created_at'),
            updated_at=data.get('updated_at')
        )
